version: "3"

services:

  jobsearch-web:
    container_name: jobsearch-web
    image: ramesesinc/jobsearch-web:2.5.01.01
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: 10m
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ./env.conf
      - ../../_res/env.conf
      - ../../_custom/env.conf
    ports:
      - "8081:8080"
    volumes:
      - ../../_custom/lgu-logo.png:/webroot/res/logo.png
